// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Dz9r5YHbWu2lNs6o0zQsgS5zGSKYZ2o',
    appId: '1:251611596478:web:b394e672f39f242800c0ef',
    messagingSenderId: '251611596478',
    projectId: 'flutter-chat-exsis',
    authDomain: 'flutter-chat-exsis.firebaseapp.com',
    storageBucket: 'flutter-chat-exsis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ZkkDo9JYadLOYwmr_0-nxCRl-a50vgI',
    appId: '1:251611596478:android:45b65e37a2a5556b00c0ef',
    messagingSenderId: '251611596478',
    projectId: 'flutter-chat-exsis',
    storageBucket: 'flutter-chat-exsis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPsXVYVZfPjB7q8cQW2FX_0x0flmNUqjA',
    appId: '1:251611596478:ios:9f8851e3062f7b2200c0ef',
    messagingSenderId: '251611596478',
    projectId: 'flutter-chat-exsis',
    storageBucket: 'flutter-chat-exsis.appspot.com',
    iosClientId: '251611596478-cdhv1i2a1tvttfp3l60jhe6jefn1rr94.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPsXVYVZfPjB7q8cQW2FX_0x0flmNUqjA',
    appId: '1:251611596478:ios:4b2d65a3abbe974c00c0ef',
    messagingSenderId: '251611596478',
    projectId: 'flutter-chat-exsis',
    storageBucket: 'flutter-chat-exsis.appspot.com',
    iosClientId: '251611596478-irhkheto8hem3qd5dg3oufm214lp7i49.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat.RunnerTests',
  );
}
